name: 'Install torchani'
description: 'Installs torchani together with all necessary dependencies, (this includes CUDA toolkit if requested)'
inputs:
  cuda:
    description: 'Whether to install cuda and cpp/cuda extensions, must be one of "cuda" or "no-cuda"'
    required: true 
    default: 'no-cuda'
  torch-version:
    description: 'Version of torch to install, must be one of "stable" or "nightly"'
    required: true
    default: 'stable'
runs: 
  using: 'composite'
  steps:
    - name: Fetch submodules
      run: git submodule update --init
      shell: bash

    - name: Install cuda if necessary
      # composite actions don't support if conditionals yet, so we just use
      # shell script
      run: |
        if [[ "${{ inputs.cuda }}" == 'cuda' ]]; then 
            source ci/install_cuda.sh
            echo "CUDA_HOME=${CUDA_HOME}" >> $GITHUB_ENV
            echo "LD_LIBRARY_PATH=${CUDA_HOME}/lib64:${LD_LIBRARY_PATH}" >> $GITHUB_ENV
            echo "PATH=${CUDA_HOME}/bin:$PATH" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Install basic packages
      run: |
        pip install --upgrade pip
        pip install twine wheel
      shell: bash

    - name: Install ${{ inputs.torch-version }} torch
      # uninstall || true prevents command from erroring out if the package can't be found
      run: |
        pip uninstall torch || true
        [[ "${{ inputs.torch-version }}" == 'stable' ]] && pip install torch==1.8.1+cu111 torchvision==0.9.1+cu111 -f https://download.pytorch.org/whl/torch_stable.html        
        [[ "${{ inputs.torch-version }}" == 'nightly' ]] && pip install --pre --upgrade torch torchvision -f https://download.pytorch.org/whl/nightly/cu111/torch_nightly.html
        echo $(python -c "import torch; print('python found torch version:', torch.__version__)")
      shell: bash

    - name: Install tests and docs requirements
      run: |
        pip install -r test_requirements.txt
        pip install -r docs_requirements.txt
      shell: bash

    - name: Install TorchANI with ${{ inputs.cuda }}
      run: |
        if [[ "${{ inputs.cuda }}" == 'cuda' ]]; then 
          echo $CUDA_HOME 
          echo $LD_LIBRARY_PATH 
          nvcc -V
          python setup.py install --ext
        else
          python setup.py install
        fi
      shell: bash

    - name: Download data files
      run: ./download.sh
      shell: bash
