name: 'Install torchani'
description: 'Checks out and installs torchani together with all necessary dependencies, (this includes CUDA toolkit if requested)'
inputs:
    token:
        description: 'Github access token'
        required: true
    python-version:
        description: 'Python version to set up'
        required: true
        default: 3.8
    cuda:
        description: 'Whether to install cuda and cpp/cuda extensions, must be one of "cuda" or "no-cuda"'
        required: true 
        default: 'no-cuda'
    torch-version:
        description: 'Version of torch to install, must be one of "stable" or "nightly"'
        required: true
        default: 'stable'
runs: 
    using: 'composite'
    steps:
        - name: Cancel Previous Runs
          uses: styfle/cancel-workflow-action@0.8.0
          with:
            access_token: ${{ inputs.token }}

        - name: Checkout TorchANI
          uses: actions/checkout@v1

        - name: Set up Python ${{ inputs.python-version }}
          uses: actions/setup-python@v2
          with:
            python-version: ${{ inputs.python-version }}

        - name: Fetch submodules
          run: git submodule update --init
        - name: Install cuda
          if: ${{ inputs.install-cuda-and-ext}}
          run: |
            source ci/install_cuda.sh
            echo "CUDA_HOME=${CUDA_HOME}" >> $GITHUB_ENV
            echo "LD_LIBRARY_PATH=${CUDA_HOME}/lib64:${LD_LIBRARY_PATH}" >> $GITHUB_ENV
            echo "PATH=${CUDA_HOME}/bin:$PATH" >> $GITHUB_ENV

        - name: Install basic packages
          run: |
            pip install --upgrade pip
            pip install twine wheel

        - name: Install stable torch
          if: ${{ inputs.torch-version == 'stable' }}
          # uninstall || true prevents command from erroring out if the package can't be found
          run: |
            pip uninstall torch || true
            pip install torch==1.8.1+cu111 torchvision==0.9.1+cu111 -f https://download.pytorch.org/whl/torch_stable.html        
              echo $(python -c "import torch; print('python found torch version:', torch.__version__)")

        - name: Install nightly torch
          if: ${{ inputs.torch-version == 'nightly' }}
          run: |
              pip uninstall torch || true
              pip install --pre --upgrade torch torchvision -f https://download.pytorch.org/whl/nightly/cu111/torch_nightly.html
              echo $(python -c "import torch; print('python found torch version:', torch.__version__)")

        - name: Install tests and docs requirements
          run: |
            pip install -r test_requirements.txt
            pip install -r docs_requirements.txt

        - name: Install TorchANI with extension
          if: ${{ inputs.cuda == 'cuda' }}
          run: |
            echo $CUDA_HOME
            echo $LD_LIBRARY_PATH
            nvcc -V
            python setup.py install --ext

        - name: Install TorchANI
          if: ${{ inputs.cuda == 'no-cuda' }}
          run: python setup.py install

        - name: Download data files
          run: ./download.sh
