FROM pytorch/pytorch:1.13.1-cuda11.6-cudnn8-devel

# environment
# NGC Container forces using TF32, disable it
ENV TORCH_ALLOW_TF32_CUBLAS_OVERRIDE=0

# Set default shell to /bin/bash
SHELL ["/bin/bash", "-cu"]

# install some packages
RUN apt-get update && \
    apt-get install -y git wget unzip

# Copy files into container
COPY . /torchani_sandbox

# Install torchani and dependencies
RUN cd /torchani_sandbox \
    && ./conda/build_conda.sh

WORKDIR /torchani_sandbox
