FROM pytorch/pytorch:2.3.0-cuda11.8-cudnn8-devel
WORKDIR /torchani_sandbox

# Set default shell to /bin/bash (otherwise it is dash)
SHELL ["/bin/bash", "-cu"]

# Install packages to run download and to detect version using setuptools-scm
RUN apt-get update && apt-get install -y git wget unzip

# Copy all repo files into the image
COPY . /torchani_sandbox

# Build conda
RUN ./conda/build_conda.sh
