# Here be tests for the active learning protocol
# NOTE: before putting this into the master branch, should come up with better names for test_al.py -- or incorporate all these tests into that file...