package:
  name: sandbox
  version: "{{ environ.get('BUILD_VERSION', '0.0.0') }}"

source:
  path: "../.."

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  # Specifying the versions is useful for solving the env faster
  host:
    - conda-forge::python={{ python }}
    - conda-forge::typing_extensions>=4.0.0
    - conda-forge::cmake
    - conda-forge::git
    - conda-forge::pip
    - conda-forge::setuptools
    - conda-forge::setuptools_scm
    - pytorch::pytorch={{ pytorch }}
    - pytorch::pytorch-cuda={{ cuda }}
    - nvidia::cuda-libraries-dev={{ cuda }}
    - nvidia::cuda-nvcc={{ cuda }}
    - nvidia::cuda-cccl={{ cuda }}
  run:
    - conda-forge::python={{ python }}
    - conda-forge::typing_extensions>=4.0.0
    - conda-forge::numpy>=1.24
    - conda-forge::h5py
    - conda-forge::tqdm
    - pytorch::pytorch={{ pytorch }}
    - pytorch::pytorch-cuda={{ cuda }}

build:
  number: 0
  string: py{{ python }}_torch{{ pytorch }}_cuda{{ cuda }}
  # The following can be used to build with the system's cuda
  # script_env:
  # - CUDA_HOME=path_to_cuda

test:
  # These are automatically added to the "run" requirements when testing
  requires:
    - conda-forge::parameterized
    - conda-forge::expecttest
  source_files:
    - tests/*
    - dataset/*
    - download.sh
  commands:
    # Download test data
    - ./download.sh
    # Cuaev test only
    - python tests/test_cuaev.py

about:
  home: https://roitberg.chem.ufl.edu
  license: MIT
  license_file: LICENSE
  summary: 'Roiberg Group Sandbox'
