package:
  name: sandbox
  version: {{ environ.get('GIT_DESCRIBE_TAG', '2.3') }}.{{ environ.get('GIT_BUILD_STR', 'dev') }}

source:
  # git_url only captures committed code
  git_url: ../../

build:
  number: 0
  string: py{{ python }}_torch{{ pytorch }}_cuda{{ cuda }}
  # The following is be used to build with the system's CUDA Toolkit,
  # if the nvidia::cuda* packages are used instead, then the next 2 lines
  # should be commented out
  script_env:
    - CUDA_HOME=/usr/local/cuda
  entry_points:
    - torchani = torchani.cli:main

#Specifying versions in the requrements.host section helps conda solve the env faster
requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    # For source.git_url
    - conda-forge::git=2.34
  host:
    - conda-forge::python={{ python }}
    - conda-forge::typing_extensions=4.11
    - conda-forge::cmake=3.29.3
    - conda-forge::pip=24.0
    - conda-forge::setuptools=69.5.1
    - conda-forge::setuptools_scm=8.1.0
    - pytorch::pytorch={{ pytorch }}
    - pytorch::pytorch-cuda={{ cuda }}
    # NOTE: This script assumes by default that the extensions are built using
    # the system's CUDA Toolkit, if this is not possible then the next 3 lines
    # should be added,
    #- nvidia::cuda-libraries-dev={{ cuda }}
    #- nvidia::cuda-nvcc={{ cuda }}
    #- nvidia::cuda-cccl={{ cuda }}
  run:
    - conda-forge::python={{ python }}
    - conda-forge::typing_extensions>=4.0.0
    - conda-forge::numpy>=1.24
    - conda-forge::h5py
    - conda-forge::tqdm
    - pytorch::pytorch={{ pytorch }}
    - pytorch::pytorch-cuda={{ cuda }}

test:
  # These are automatically added to the "run" requirements when testing
  requires:
    - conda-forge::parameterized=0.9.0
    - conda-forge::expecttest=0.2.1
  source_files:
    - tests/*
    - dataset/*
    - download.sh
  commands:
    # Download test data
    - ./download.sh
    # Cuaev test only
    - python tests/test_cuaev.py

about:
  home: https://roitberg.chem.ufl.edu
  license: MIT
  license_file: LICENSE
  summary: Roiberg Group Sandbox
