package:
  name: "{{ environ.get('PACKAGE_NAME') }}"
  version: "{{ environ.get('BUILD_VERSION') }}"

source:
  path: "{{ environ.get('PACKAGE_ROOT') }}"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - git
    - pip
    - setuptools
    - setuptools_scm
    - python={{ environ.get('PYTHON_VERSION') }}
    #- pytorch::pytorch={{ environ.get('PYTORCH_VERSION') }}
    #- pytorch::pytorch-cuda={{ environ.get('CUDA_VERSION') }}
    #- nvidia::cuda-libraries-dev={{ environ.get('CUDA_VERSION') }}
    #- nvidia::cuda-nvcc={{ environ.get('CUDA_VERSION') }}
    #- nvidia::cuda-cccl={{ environ.get('CUDA_VERSION') }}
  run:
    - python={{ environ.get('PYTHON_VERSION') }}
    - pytorch::pytorch={{ environ.get('PYTORCH_VERSION') }}
    - pytorch::pytorch-cuda={{ environ.get('CUDA_VERSION') }}
    - numpy>=1.24
    - typing_extensions>=4.0.0
    - h5py
    - tqdm

build:
  number: 0
  string: py{{ environ.get('PYTHON_VERSION') }}_torch{{ environ.get('PYTORCH_VERSION') }}_cuda{{ environ.get('CUDA_VERSION')}}
  script: "DISABLE_NINJA=1 {{ PYTHON }} -m pip install --no-deps --no-build-isolation --config-settings=--global-option=ext-all-sms -v ."

test:
  # These are automatically added to the "run" requirements when testing
  requires:
    - parameterized
    - expecttest
  source_files:
    - tests/*
    - dataset/*
    - download.sh
  commands:
    # Download test data
    - ./download.sh
    # Cuaev test only
    - python tests/test_cuaev.py

about:
  home: https://roitberg.chem.ufl.edu
  license: MIT
  license_file: LICENSE
  summary: 'Roiberg Group Sandbox'
