package:
  name: sandbox
  version: "{{ environ.get('BUILD_VERSION') }}"

source:
  path: "{{ environ.get('SOURCE_ROOT_DIR') }}"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - python {{ python }}
    - setuptools_scm
    - cmake
    - ninja
    - importlib_metadata
    - lark-parser
    - requests
    - h5py
    - defaults::numpy >=1.18
    {{ environ.get('CONDA_PYTORCH_CONSTRAINT') }}
    {{ environ.get('CONDA_CUDATOOLKIT_CONSTRAINT') }}

  run:
    - python {{ python }}
    - setuptools
    - importlib_metadata
    - lark-parser
    - requests
    - h5py
    - defaults::numpy >=1.18
    {{ environ.get('CONDA_PYTORCH_CONSTRAINT') }}
    {{ environ.get('CONDA_CUDATOOLKIT_CONSTRAINT') }}

build:
  number: 1
  string: py{{py}}_torch1.9.0_cuda11.1
  script:
    - "{{ PYTHON }} setup.py install --ext-all-sms"

test:
  imports:
    - torchani
    - torchani.cuaev

about:
  home: https://roitberg.chem.ufl.edu
  license: MIT
  license_file: LICENSE
  summary: 'Roiberg Group Sandbox'
