package:
  name: "{{ environ.get('PACKAGE_NAME') }}"
  version: "{{ environ.get('BUILD_VERSION') }}"

source:
  path: "{{ environ.get('SOURCE_ROOT_DIR') }}"

requirements:
  build:
    - python={{ environ.get('PYTHON_VERSION') }}
    - pip
    - git
    #- cmake
    #- ninja
    - setuptools
    - setuptools_scm
    #- {{ compiler('c') }}
    #- {{ compiler('cxx') }}
    #- nvidia::cuda-toolkit={{ environ.get('CUDA_VERSION') }}
    #- nvidia::cuda-compiler={{ environ.get('CUDA_VERSION') }}
    #- pytorch::pytorch={{ environ.get('PYTORCH_VERSION') }}
    #- pytorch::pytorch-cuda={{ environ.get('CUDA_VERSION') }}

  run:
    - python={{ environ.get('PYTHON_VERSION') }}
    - numpy >={{ environ.get('NUMPY_CONSTRAINT')}}
    - typing_extensions>=4.0.0
    - lark-parser
    - h5py
    - tqdm
    - ase
    #- nvidia::cuda-toolkit={{ environ.get('CUDA_VERSION') }}
    #- nvidia::cuda-compiler={{ environ.get('CUDA_VERSION') }}
    - pytorch::pytorch={{ environ.get('PYTORCH_VERSION') }}
    - pytorch::pytorch-cuda={{ environ.get('CUDA_VERSION') }}

build:
  number: 0
  string: py{{ environ.get('PYTHON_VERSION') }}_torch{{ environ.get('PYTORCH_VERSION') }}_cuda{{ environ.get('CUDA_VERSION')}}
  script:
    #- "{{ PYTHON }} -m pip install . --global-option='--ext-all-sms' -vvv --no-deps"
    - "{{ PYTHON }} -m pip install . -vvv --no-deps"

#test:
  #imports:
    #- torchani
    #- torchani.cuaev
    #- torchani.mnp
  #source_files:
    #- tests/*
    #- download.sh
    #- dataset/*
  #commands:
    #- pip install pytest pynvml ase parameterized expecttest
    #- ./download.sh
    ## cuaev test
    #- python tests/test_cuaev.py

about:
  home: https://roitberg.chem.ufl.edu
  license: MIT
  license_file: LICENSE
  summary: 'Roiberg Group Sandbox'
